# Generated by Django 5.1.4 on 2024-12-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty_hunter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
